<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="jayesh-pc" failures="5" tests="17" name="Specific Test" time="0.512" errors="0" timestamp="2022-04-13T12:16:05 IST">
  <testcase classname="TestCases.HardAssertionTest" name="method11" time="0.051">
    <failure type="java.lang.AssertionError" message="If doesn&amp;apos;t match = failed method1 expected [121] but found [12]">
      <![CDATA[java.lang.AssertionError: If doesn't match = failed method1 expected [121] but found [12]
at TestCases.HardAssertionTest.method11(HardAssertionTest.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- method11 -->
  <testcase classname="TestCases.HardAssertionTest" name="method2" time="0.009"/>
  <testcase classname="TestCases.HardAssertionTest" name="method3" time="0.006"/>
  <testcase classname="TestCases.HardAssertionTest" name="method4" time="0.003"/>
  <testcase classname="TestCases.HardAssertionTest" name="method5" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestCases.HardAssertionTest.method5(HardAssertionTest.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- method5 -->
  <testcase classname="TestCases.HardAssertionTest" name="method6" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestCases.HardAssertionTest.method6(HardAssertionTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- method6 -->
  <testcase classname="TestCases.GroupTest" name="method1" time="0.011"/>
  <testcase classname="TestCases.GroupTest" name="method2" time="0.004"/>
  <testcase classname="TestCases.GroupTest" name="method3" time="0.008"/>
  <testcase classname="TestCases.GroupTest" name="method4" time="0.008"/>
  <testcase classname="TestCases.GroupTest" name="method5" time="0.012"/>
  <testcase classname="TestCases.GroupTest" name="method6" time="0.032"/>
  <testcase classname="TestCases.SoftAssertionTest" name="test1" time="0.019">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	does it failed? expected [Automation1] but found [Automation],
	Failed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
does it failed? expected [Automation1] but found [Automation],
Failed expected [false] but found [true]
at TestCases.SoftAssertionTest.test1(SoftAssertionTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="TestCases.SoftAssertionTest" name="test2" time="0.014">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	its failing expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
its failing expected [true] but found [false]
at TestCases.SoftAssertionTest.test2(SoftAssertionTest.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="TestCases.Priority1" name="method2" time="0.004"/>
  <testcase classname="TestCases.Priority1" name="method3" time="0.003"/>
  <testcase classname="TestCases.Priority1" name="method4" time="0.002"/>
  <testcase classname="TestCases.Priority1" name="method5" time="0.0">
    <ignored/>
  </testcase> <!-- method5 -->
  <testcase classname="TestCases.Priority1" name="method1" time="0.0">
    <ignored/>
  </testcase> <!-- method1 -->
</testsuite> <!-- Specific Test -->
